### ISSUE TITLE
getNodeJunctionDemandIndex can not retrieves the demand index for node list as input parameter

### ISSUE THREAD

**Issue by sdlj2008** [OpenWaterAnalytics/EPyT#20]
The statement: value = [[0 for i in range(len(nodeIndex))] for j in range(len(demandName))], is not in the right place.

            if not isList(nodeIndex):
                value = []
                for i in range(len(demandName)):
                    demandNameIn = demandName[i + 1]
                    value.append(self.api.ENgetdemandindex(nodeIndex, demandNameIn[nodeIndex - 1]))
            else:
                for i in range(len(demandName)):
                    demandNameIn = demandName[i + 1]
                    **value = [[0 for i in range(len(nodeIndex))] for j in range(len(demandName))]**
                    for j in range(len(nodeIndex)):
                        value[i][j] = self.api.ENgetdemandindex(nodeIndex[j], demandNameIn[nodeIndex[j]])

The following code can retrieve the right result:

            if not isList(nodeIndex):
                value = []
                for i in range(len(demandName)):
                    demandNameIn = demandName[i + 1]
                    value.append(self.api.ENgetdemandindex(nodeIndex, demandNameIn[nodeIndex - 1]))
            else:
                **value = [[0 for i in range(len(nodeIndex))] for j in range(len(demandName))]**
                for i in range(len(demandName)):
                    demandNameIn = demandName[i + 1]
                    for j in range(len(nodeIndex)):
                        value[i][j] = self.api.ENgetdemandindex(nodeIndex[j], demandNameIn[**nodeIndex[j] - 1**])

**Comment by Mariosmsk** [comment]
Thank you @sdlj2008 !!
