### ISSUE TITLE
EPANET-MSX cannot be loaded on Linux

### ISSUE THREAD

**Issue by andreArtelt** [OpenWaterAnalytics/EPyT#37]
When I try to load a .msx file on Linux, I run into several issues:
1. Path to epanetmsx.so is wrong -- it is the same Windows path for all platforms:
![msx](https://github.com/OpenWaterAnalytics/EPyT/assets/15552483/317e636a-bad6-4651-9d0e-6e3a60d2ead3)

2. When I fix this, I get an error that libepanet.so can not be loaded. It seems that epanetmsx.so was linked against libepanet.so which is not shipped (only libepanet2_2.so is included in EPyT):
![missing](https://github.com/OpenWaterAnalytics/EPyT/assets/15552483/130d7bf0-7e5d-407a-b739-57cf2f242684)

**Comment by Mariosmsk** [comment]
Hi @andreArtelt,

Please execute the following command (in folder glnx):

`sudo cp libepanet2.so /lib/x86_64-linux-gnu/libepanet.so`

Version: epyt==1.0.9b4

The test files look fine here: https://github.com/OpenWaterAnalytics/EPyT/actions/runs/8712186456

**Comment by andreArtelt** [comment]
Seems to be solved with the latest version.
